In [3]:
import numpy as np

In [4]:
list1=[1,2,3,4,5,]
arr1=np.array(list1)
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
#2 dimensional array
list2=[
    [1,2,3,],
    [8,9,7]
]

arr2=np.array(list2, dtype='float32')
arr2

array([[1., 2., 3.],
       [8., 9., 7.]], dtype=float32)

In [6]:
#Create a length 10 integer array filled with zeros.
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
#creating 2 dimensional array using zeros
np.zeros((2,4),dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:

#creating arrays 2x4 using ones
np.ones((2,4),dtype='float')

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
#creating 2x4 arrays filled with 3.14
np.full((2,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [10]:
#in for loop did another way
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.random.random((3,3))

array([[0.96854683, 0.22750207, 0.870047  ],
       [0.88447087, 0.60991247, 0.01621766],
       [0.90782391, 0.94313533, 0.6370743 ]])

In [12]:
np.random.normal(0,1,(3,3))

array([[-0.7397219 ,  0.43583562,  1.01638604],
       [ 0.24020842, -1.25970329,  0.19886263],
       [ 0.33865695, -1.22149568,  1.26107907]])

In [13]:
#3x3 array having mean 1 sd 2
np.random.normal(1,2,(3,3))

array([[ 4.25029331,  0.6545703 ,  2.46137102],
       [-0.70015037,  1.97949094,  1.10060949],
       [-1.76697895,  3.91089118,  0.11005046]])

In [14]:
np.random.randint(0,10,(3,3))

array([[9, 1, 5],
       [3, 1, 0],
       [7, 2, 7]])

In [15]:
sample_array=np.array([ [1,2,3],
    [4,7,8],
    [1,7,9]
                      ])
print(f"The dimension of sample arrar is {sample_array.ndim}")

The dimension of sample arrar is 2


In [16]:
print(f"The shape of sample arrar is {sample_array.shape}")

The shape of sample arrar is (3, 3)


In [17]:
print(f"The size of sample arrar is {sample_array.size}")

The size of sample arrar is 9


In [18]:
list1=[1,2,3,4,5,"sarika"]
arr1=np.array(list1)
arr1

array(['1', '2', '3', '4', '5', 'sarika'], dtype='<U11')

In [21]:
import numpy as np 
arr01=np.array([1,2,3,4])
arr01

array([1, 2, 3, 4])

In [27]:
arr02=np.array([1,2,3,4,"Sarika"],dtype=int)
arr02

ValueError: invalid literal for int() with base 10: 'Sarika'

In [28]:
arr03=np.array([1,2,3,4,"Sarika"],dtype=float)
arr03

ValueError: could not convert string to float: 'Sarika'

In [29]:
arr04=np.array([1,2,3,4,"Sarika"],dtype=str)
arr04

array(['1', '2', '3', '4', 'Sarika'], dtype='<U6')

In [30]:
a=np.array([0,1,2,3,4,])
print(f'1st item:{a[0]}')
print(f'2nd item:{a[1]}')
print(f'3rd item:{a[2]}')
print(f'4th item:{a[3]}')

1st item:0
2nd item:1
3rd item:2
4th item:3


In [41]:
a2=np.array([[0,1,2,3,4],
             [9,0,2,1,3]
            ])
print(a2[0,0])
print(a2[0,1])
print(a2[0,2])
print(a2[1,0])
print(a2[1,1])
print(a2[1,2])


0
1
2
9
0
2


In [42]:
#slicing element from 2nd to 4
b=np.array([0,1,2,3,4,])
bslice=b[1:4]
print(bslice)


[1 2 3]


In [45]:
#after fifth element slice
bslice=b[4:]
print(bslice)

[4]


In [46]:
#left to right
bslice=b[-3:-1]
print(bslice)

[2 3]


In [50]:
arr2=np.array([
    [11,12,13],
    [14,17,18],
    [10,31,32]
])
arr2[1,1:]

array([17, 18])

In [53]:
#create sample array
base_arr=np.array([1,2,3,4,7,8])
print(base_arr)

[1 2 3 4 7 8]


In [55]:
copy_arr=base_arr.copy()
print(copy_arr)

[1 2 3 4 7 8]


In [62]:
copy_arr=base_arr.copy()
copy_arr1=base_arr
print(copy_arr)

[1 2 3 4 7 8]


In [63]:
print(f"""Do original array and copy array shares a same memory?
    Ans:{np.shares_memory(base_arr,copy_arr)}""")


Do original array and copy array shares a same memory?
    Ans:False


In [66]:
view_arr=base_arr.view()
print(view_arr)

[1 2 3 4 7 8]


In [68]:
print(f"""Do view array and copy array shares a same memory?
    Ans:{np.shares_memory(view_arr,copy_arr)}""")

Do view array and copy array shares a same memory?
    Ans:False
